import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight: ["400", "600", "800"],
  style: "normal",
  subsets: ["latin"],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`${poppins.className} text-white bg-gray`}>{children}</body>
    </html>
  )
}
